; See https://github.com/docker/for-linux/issues/264
; The `client_host` below may optionally be replaced with `discover_client_host=yes`
xdebug.client_host = host.docker.internal
opcache.validate_timestamps = 1
